In [5]:
# import Pkg
# Pkg.add("HTTP")
# Pkg.add("JSON")
# Pkg.add("YAML")
# Pkg.add("URIs")

In [85]:
include("../src/QuantumAnnealers.jl")
using .QuantumAnnealers
using JSON, HTTP, URIs

In [86]:
using YAML

# Load your Dwave API key into config
config = YAML.load_file("../secrets.yaml");
QuantumAnnealers.init(config["dwave"]["key"]);
solver=Dict("topology__type"=>"pegasus")

Dict{String, String} with 1 entry:
  "topology__type" => "pegasus"

In [16]:
# Q = Dict(0 => Dict(1 => -1.0), 1 => Dict(2 => -1.0), 0 => Dict(2 => 2.0));
# result = QuantumAnnealers.solve_qubo(solver["topology__type"], Q)

# println("Result: $result")

In [11]:
# Define your Ising problem
h = Dict(1 => -1, 2 => -1)  # Linear coefficients
J = Dict((1, 2) => 1)     # Quadratic coefficients

# Submit the Ising problem to the solver
job_id = QuantumAnnealers.ising_sample(solver["topology__type"], h, J)

# Assuming the job is complete, fetch the results
results = QuantumAnnealers.fetch_results(job_id)

println(results)

HTTP.Exceptions.StatusError: HTTP.Exceptions.StatusError(404, "POST", "/sapi/solvers/pegasus/jobs/", HTTP.Messages.Response:
"""
HTTP/1.1 404 Not Found
Date: Sun, 05 Nov 2023 20:21:22 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Connection: keep-alive
Server: nginx

404: Not Found""")

In [279]:
QuantumAnnealers.solvers_available()

hybrid_binary_quadratic_model_version2
	 Status: ONLINE	 Avg Load: 0.0 
hybrid_discrete_quadratic_model_version1
	 Status: ONLINE	 Avg Load: 0.0 
Advantage_system4.1
	 Status: ONLINE	 Avg Load: 0.01 
hybrid_constrained_quadratic_model_version1
	 Status: ONLINE	 Avg Load: 0.0 
Advantage2_prototype1.1
	 Status: ONLINE	 Avg Load: 0.0 
Advantage_system6.3
	 Status: ONLINE	 Avg Load: 0.01 


6-element Vector{Any}:
 Dict{String, Any}("status" => "ONLINE", "properties" => Dict{String, Any}("maximum_number_of_biases" => 200000000, "parameters" => Dict{String, Any}("time_limit" => "Maximum requested runtime in seconds."), "quota_conversion_rate" => 20, "maximum_time_limit_hrs" => 24.0, "minimum_time_limit" => Any[Any[1, 3.0], Any[1024, 3.0], Any[4096, 10.0], Any[10000, 40.0], Any[30000, 200.0], Any[100000, 600.0], Any[1000000, 600.0]], "maximum_number_of_variables" => 1000000, "supported_problem_types" => Any["bqm"], "category" => "hybrid", "version" => "2.2"), "id" => "hybrid_binary_quadratic_model_version2", "description" => "Hybrid solver for general BQM problems", "avg_load" => 0.0)
 Dict{String, Any}("status" => "ONLINE", "properties" => Dict{String, Any}("maximum_number_of_biases" => 5000000000, "parameters" => Dict{String, Any}("time_limit" => "Maximum requested runtime in seconds."), "quota_conversion_rate" => 20, "maximum_number_of_cases" => 500000, "maximum_time_limi

In [280]:
# r2 = session.get(f"{SAPI_HOME}/solvers/remote/{qpu_solver}")
# r2 = r2.json()
response = HTTP.request("GET", QuantumAnnealers.BASE_URL * "/solvers/remote/Advantage_system6.3", QuantumAnnealers.headers )


HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Mon, 06 Nov 2023 06:03:02 GMT
Content-Type: application/vnd.dwave.sapi.solver-definition+json; version=2.0.0
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Encoding: gzip

{"id":"Advantage_system6.3","status":"ONLINE","description":"Advantage performance update","properties":{"num_qubits":5760,"qubits":[30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,

In [281]:
res = JSON.parse(String(response.body))


Dict{String, Any} with 5 entries:
  "status"      => "ONLINE"
  "properties"  => Dict{String, Any}("problem_run_duration_range"=>Any[0.0, 1.0…
  "id"          => "Advantage_system6.3"
  "description" => "Advantage performance update"
  "avg_load"    => 0.01

In [282]:
res["properties"]

Dict{String, Any} with 30 entries:
  "problem_run_duration_range"         => Any[0.0, 1.0e6]
  "programming_thermalization_range"   => Any[0.0, 10000.0]
  "readout_thermalization_range"       => Any[0.0, 10000.0]
  "couplers"                           => Any[Any[30, 31], Any[31, 32], Any[32,…
  "supported_problem_types"            => Any["ising", "qubo"]
  "j_range"                            => Any[-1.0, 1.0]
  "qubits"                             => Any[30, 31, 32, 33, 34, 35, 36, 37, 3…
  "problem_timing_data"                => Dict{String, Any}("reverse_annealing_…
  "anneal_offset_ranges"               => Any[Any[0.0, 0.0], Any[0.0, 0.0], Any…
  "parameters"                         => Dict{String, Any}("anneal_schedule"=>…
  "chip_id"                            => "Advantage_system6.3"
  "quota_conversion_rate"              => 1
  "h_range"                            => Any[-4.0, 4.0]
  "default_programming_thermalization" => 1000.0
  "num_reads_range"                    => Any[1,

In [298]:
#Ising Sampling

# biases = Dict("x"=> -0.5, "y"=> 0.5, "xy"=> -1)
biases = Dict("x"=> 4.0, "y"=> 4.0, "xy"=> -1)
qubits = res["properties"]["qubits"]
couplers = res["properties"]["couplers"]
xy = couplers[1]

2-element Vector{Any}:
 30
 31

In [299]:
using Base64

# Assuming `qubits`, `xy`, and `biases` are predefined similar to your Python code
lin_vec = fill(0.0, length(qubits))  # Create a vector filled with NaN
lin_vec[findfirst(==(xy[1]), qubits)] = biases["x"]
lin_vec[findfirst(==(xy[2]), qubits)] = biases["y"]

# Encoding the vector to base64
lin_vec_bytes = Vector{UInt8}(undef, sizeof(Float64) * length(lin_vec))
for (i, val) in enumerate(lin_vec)
    reinterpret(UInt8, [val]) |> (x -> copyto!(lin_vec_bytes, (i-1)*8+1, x, 1, 8))
end
lin = base64encode(lin_vec_bytes)

# Similar process for quad_vec
quad_vec = fill(0.0, length(couplers))
quad_vec[1] = biases["xy"]
quad_vec_bytes = Vector{UInt8}(undef, sizeof(Float64) * length(quad_vec))
for (i, val) in enumerate(quad_vec)
    reinterpret(UInt8, [val]) |> (x -> copyto!(quad_vec_bytes, (i-1)*8+1, x, 1, 8))
end
quad = base64encode(quad_vec_bytes)


"AAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" ⋯ 427250 bytes ⋯ "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

In [303]:
# lin
conditions = Dict("solver" => "Advantage_system6.3", 
                "label" => "QPU REST submission 1", 
                "data" => Dict("format" => "qp", "lin" => lin, "quad" => quad),
                "type" => "ising",
                "params" => Dict("num_reads" => 1)
                )

Dict{String, Any} with 5 entries:
  "label"  => "QPU REST submission 1"
  "data"   => Dict("quad"=>"AAAAAAAA8L8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA…
  "solver" => "Advantage_system6.3"
  "params" => Dict("num_reads"=>1)
  "type"   => "ising"

In [304]:
  response2 = HTTP.request("POST", QuantumAnnealers.BASE_URL * "/problems", QuantumAnnealers.headers,
    body = JSON.json(conditions) )

HTTP.Messages.Response:
"""
HTTP/1.1 201 Created
Date: Mon, 06 Nov 2023 06:09:42 GMT
Content-Type: application/vnd.dwave.sapi.problems+json; version=2.1.0; charset=utf-8
Content-Length: 31554
Connection: keep-alive
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

{"status":"COMPLETED","id":"4ebbb0d0-9a13-49fc-842d-88f7cca15936","solver":"Advantage_system6.3","type":"ising","submitted_on":"2023-11-06T06:09:42.486921Z","label":"QPU REST submission 1","solved_on":"2023-11-06T06:09:42.823467Z","answer":{"solutions":"PtTC8vf1H6Tsbr4b2Q/lH1yYgxDHYOGuHOavOzyQH/py4rstKPWhU1zhaNKg3ADt2DFEaurFocSaqsQZotuhO2pnYbsu+ci69PeChBhkakcis1EgWmU4j9bb420dhYjso7g1Sm9bJqy4nh0s26CTwhIjoIv5IKkqP6zLCsUcKyqRSliWliqQxWsRMGBX7EXmHdrjP/AUE832h6N8Kw3pLi/vCUgk/RNX/egk0vFm+27ju/TjeXRqnvnx0DeTHuoIvNgXkzwxgYKucQ+3D3ubgfR9ZeQ7RGVgNG/CdEy+1PftVmvmaJaamozo5bdFUgrGUi86XLhp7JtVbGpt97oDSp6KvUDAnqzwVpIu6rZgsj0Iw+IWTy1MG3qYnQIiaH7TSfWkwjZQ/cS4MgrN3E3dMS4OB7NatnCE6jM/fat8fWo6JwpFj4XLmBcx8THa

In [305]:
res2 = JSON.parse(String(response2.body))

Dict{String, Any} with 8 entries:
  "label"        => "QPU REST submission 1"
  "status"       => "COMPLETED"
  "submitted_on" => "2023-11-06T06:09:42.486921Z"
  "id"           => "4ebbb0d0-9a13-49fc-842d-88f7cca15936"
  "solver"       => "Advantage_system6.3"
  "solved_on"    => "2023-11-06T06:09:42.823467Z"
  "type"         => "ising"
  "answer"       => Dict{String, Any}("timing"=>Dict{String, Any}("qpu_delay_ti…

In [306]:
res2["id"]

"4ebbb0d0-9a13-49fc-842d-88f7cca15936"

In [307]:
response3 = HTTP.request("GET", QuantumAnnealers.BASE_URL * "/problems/$(res2["id"])/answer", QuantumAnnealers.headers )

HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Date: Mon, 06 Nov 2023 06:09:48 GMT
Content-Type: application/vnd.dwave.sapi.problem-answer+json; version=2.1.0; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: nginx
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Encoding: gzip

{"answer":{"solutions":"PtTC8vf1H6Tsbr4b2Q/lH1yYgxDHYOGuHOavOzyQH/py4rstKPWhU1zhaNKg3ADt2DFEaurFocSaqsQZotuhO2pnYbsu+ci69PeChBhkakcis1EgWmU4j9bb420dhYjso7g1Sm9bJqy4nh0s26CTwhIjoIv5IKkqP6zLCsUcKyqRSliWliqQxWsRMGBX7EXmHdrjP/AUE832h6N8Kw3pLi/vCUgk/RNX/egk0vFm+27ju/TjeXRqnvnx0DeTHuoIvNgXkzwxgYKucQ+3D3ubgfR9ZeQ7RGVgNG/CdEy+1PftVmvmaJaamozo5bdFUgrGUi86XLhp7JtVbGpt97oDSp6KvUDAnqzwVpIu6rZgsj0Iw+IWTy1MG3qYnQIiaH7TSfWkwjZQ/cS4MgrN3E3dMS4OB7NatnCE6jM/fat8fWo6JwpFj4XLmBcx8THagUln3xpnqFhDUrXH8RyPQFEqwp6qEZb+X7C/VTnExJ6rTR+mrgV2PzFye04Ow3dAxPx6PMh2tamw8nGKB3LJ1VNm4q/2iur6/LZMhJYRdY05lpLP+688li8LSi/4pF10+YNBOmuTrlTjvqMWPvzHaNNL2+WCuW4n/tYkd5O/Q817tkzq+La

In [308]:
res3 = JSON.parse(String(response3.body))

Dict{String, Any} with 1 entry:
  "answer" => Dict{String, Any}("timing"=>Dict{String, Any}("qpu_delay_time_per…

In [309]:
@info res3["answer"]["timing"]["qpu_access_time"]
using Base64

# Assuming `r4` is a dictionary-like structure obtained from a JSON response
qpu_access_time = res3["answer"]["timing"]["qpu_access_time"]

# Decode the base64-encoded energies
energies_encoded = res3["answer"]["energies"]
energies_bytes = base64decode(energies_encoded)

# Convert the byte array into an array of floats (doubles)
energies = reinterpret(Float64, energies_bytes)

# Print the result
println("Found lowest energy $(minimum(energies)) in $qpu_access_time microseconds.")



Found lowest energy -9.0 in 16158.21 microseconds.


┌ Info: 16158.21
└ @ Main /Users/javier/Desktop/Julia/QuantumAnnealers.jl/examples/simpleCall.ipynb:1


In [310]:
energies

1-element reinterpret(Float64, ::Vector{UInt8}):
 -9.0

In [311]:
res3["answer"]
# reinterpret(Float64, base64decode(res3["answer"]["energies"]))

Dict{String, Any} with 7 entries:
  "timing"           => Dict{String, Any}("qpu_delay_time_per_sample"=>20.54, "…
  "num_variables"    => 5760
  "format"           => "qp"
  "active_variables" => "HgAAAB8AAAAgAAAAIQAAACIAAAAjAAAAJAAAACUAAAAmAAAAJwAAAC…
  "energies"         => "AAAAAAAAIsA="
  "num_occurrences"  => "AQAAAA=="
  "solutions"        => "PtTC8vf1H6Tsbr4b2Q/lH1yYgxDHYOGuHOavOzyQH/py4rstKPWhU1…

In [312]:
# reinterpret(Float64, base64decode(res3["answer"]["active_variables"])[1:Int(10*80)])
# sign.(reinterpret(Float64, base64decode(res3["answer"]["solutions"])))
# base64decode(res3["answer"]["solutions"])

# Function to unpack bits to Ising values (-1 or +1)
function unpack_bits_to_ising(decoded_bytes)
    # Initialize an empty array to store the Ising problem variables
    ising_solutions = Int[]

    # Iterate over each byte
    for byte in decoded_bytes
        # Iterate over each bit in the byte
        for i in 0:7
            # Extract the bit using bitwise AND and shift
            bit = (byte >>> i) & 0x01
            # Map 0 to -1, 1 stays 1 for Ising model
            ising_value = (bit == 0) ? -1 : 1
            # Append the Ising value to the solutions array
            push!(ising_solutions, ising_value)
        end
    end

    return ising_solutions
end


function bytes_to_ising_solutions(bytes)
    # Initialize an array to store the Ising problem solutions
    ising_solutions = Int[]

    # Iterate through each byte
    for byte in bytes
        # Iterate through each bit in the byte in little-endian order
        for bit_index in 0:7
            # Extract the bit
            bit = (byte >> bit_index) & 0x01
            # Convert 0 to -1 for Ising representation
            ising_value = (bit == 0) ? -1 : 1
            push!(ising_solutions, ising_value)
        end
    end

    return ising_solutions
end

bytes_to_ising_solutions (generic function with 1 method)

In [313]:
spins = unpack_bits_to_ising(base64decode(res3["answer"]["solutions"]))
spins = bytes_to_ising_solutions(base64decode(res3["answer"]["solutions"]))

5616-element Vector{Int64}:
 -1
  1
  1
  1
  1
  1
 -1
 -1
 -1
 -1
  ⋮
  1
 -1
 -1
 -1
  1
 -1
  1
  1
 -1

In [314]:
spins

5616-element Vector{Int64}:
 -1
  1
  1
  1
  1
  1
 -1
 -1
 -1
 -1
  ⋮
  1
 -1
 -1
 -1
  1
 -1
  1
  1
 -1

In [271]:
reshape(spins, :,10)'

10×5632 adjoint(::Matrix{Int64}) with eltype Int64:
  1   1  -1   1  -1   1  -1  -1   1  …   1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1  -1   1  -1   1  -1  -1  -1     -1  -1  -1  -1  -1  -1   1   1  -1
  1   1  -1   1  -1  -1  -1  -1  -1      1  -1  -1  -1  -1  -1  -1  -1  -1
  1  -1   1   1  -1   1   1   1  -1     -1  -1  -1  -1  -1  -1   1  -1  -1
  1  -1  -1  -1   1  -1   1   1  -1     -1  -1  -1  -1  -1  -1   1   1   1
  1  -1   1   1  -1   1  -1  -1   1  …  -1  -1  -1  -1  -1  -1  -1   1   1
  1   1   1  -1   1  -1   1   1  -1     -1  -1  -1  -1  -1  -1   1   1  -1
  1   1   1  -1  -1  -1  -1  -1   1      1  -1  -1  -1  -1  -1  -1  -1  -1
  1  -1   1   1  -1  -1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1   1
 -1  -1  -1  -1  -1  -1   1   1  -1     -1  -1  -1  -1  -1  -1  -1   1   1

In [258]:
reshape(spins, :,10)'

10×5632 adjoint(::Matrix{Int64}) with eltype Int64:
 -1   1  -1  -1  -1  -1  -1  -1   1  …  -1  -1  -1  -1  -1  -1   1   1  -1
  1   1  -1   1   1   1  -1  -1   1     -1  -1  -1  -1  -1  -1  -1   1   1
  1  -1  -1   1  -1   1  -1  -1   1      1  -1  -1  -1  -1  -1   1   1   1
  1   1  -1  -1  -1   1  -1  -1   1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1   1  -1   1  -1   1  -1  -1   1     -1  -1  -1  -1  -1  -1  -1   1   1
  1  -1   1   1  -1  -1  -1  -1  -1  …  -1  -1  -1  -1  -1  -1  -1   1   1
  1  -1   1   1  -1  -1  -1  -1  -1      1  -1  -1  -1  -1  -1   1  -1   1
 -1   1   1   1   1  -1  -1  -1  -1      1  -1  -1  -1  -1  -1  -1   1  -1
  1   1  -1   1  -1   1  -1  -1  -1      1  -1  -1  -1  -1  -1  -1   1  -1
  1   1   1  -1  -1  -1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1

In [248]:
reshape(spins, :,10)'
# spins[1:20]

10×5632 adjoint(::Matrix{Int64}) with eltype Int64:
  1   1  -1   1  -1  -1  -1  -1  -1  …  -1  -1  -1  -1  -1  -1   1  -1  -1
  1  -1  -1   1  -1  -1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1   1  -1
 -1   1  -1   1   1  -1  -1  -1  -1      1  -1  -1  -1  -1  -1   1   1   1
 -1  -1  -1  -1   1   1  -1  -1  -1     -1  -1  -1  -1  -1  -1   1  -1  -1
 -1   1   1   1  -1  -1  -1  -1  -1      1  -1  -1  -1  -1  -1  -1   1  -1
 -1  -1   1  -1  -1   1  -1  -1   1  …   1  -1  -1  -1  -1  -1   1  -1   1
  1  -1  -1  -1   1   1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1   1   1
 -1   1   1  -1  -1   1  -1  -1  -1     -1  -1  -1  -1  -1  -1  -1  -1  -1
  1  -1   1  -1  -1   1  -1  -1   1     -1  -1  -1  -1  -1  -1   1   1  -1
  1   1   1   1  -1   1  -1  -1   1     -1  -1  -1  -1  -1  -1  -1   1   1

In [315]:
reinterpret(Int32, base64decode(res3["answer"]["active_variables"]))

5614-element reinterpret(Int32, ::Vector{UInt8}):
   30
   31
   32
   33
   34
   35
   36
   37
   38
   39
    ⋮
 5721
 5722
 5723
 5724
 5725
 5726
 5727
 5728
 5729